# conf/logging.yaml
version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s | %(levelname)s | %(name)s | %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    level: INFO
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    formatter: standard
    level: INFO
    filename: logs/pipeline.log
    mode: a
    encoding: utf-8

root:
  level: INFO
  handlers: [console, file]
